### ISSUE TITLE
How to convert PDF to PNG?

### ISSUE THREAD

**Issue by awkrail** [DS4SD/DocLayNet#10]
Hi, thank you for sharing the great work! 

I am curious how to convert PDF files into images.
The main reason for this is to use our custom dataset based on the model pre-trained on DocKayNet.
Could you share the detailed procedures (e.g., which commands do you use, such as pdftoppm)?

Thanks!

**Comment by dolfim-ibm** [comment]
Hi @misogil0116, the dataset already contains both PDF and PNG for all pages.
If you are interested into how we prepare the dataset, you can see more in our examples gallery https://ds4sd.github.io/deepsearch-toolkit/gallery/

**Comment by cau-git** [comment]
Hi @awkrail, for the reproduction of the training images in DocLayNet, you can use the following toolchain:

1. Convert to PNG at 72 dpi resolution
```
pdftoppm -png -singlefile -cropbox -r 72 input.pdf output.png
```
2. Resize the resulting PNG to 1025x1025, e.g. with `open-cv` or `pillow`.
```python
...
# Open CV
img_resized = cv2.resize(img_original, (1025, 1025), interpolation=cv2.INTER_CUBIC)
```

**Comment by awkrail** [comment]
@dolfim-ibm @cau-git 
Thank you for your comments. I can reproduce it in my environment! Close this issue.
