### ISSUE TITLE
Make the datasets available via Hugging Face datasets 

### ISSUE THREAD

**Issue by davanstrien** [DS4SD/DocLayNet#13]
First, thanks for releasing such a helpful dataset! 

It would be great to have this dataset available on the Hugging Face Hub as a [dataset](https://huggingface.co/datasets). Since the annotations are stored in the COCO format, this should be relatively easy. If the creators of the dataset are interested, I'm happy to help with this.

**Comment by PeterStaar-IBM** [comment]
@davanstrien Yes, we would be very interested! Just give us some pointers and we get started!

**Comment by davanstrien** [comment]
@PeterStaar-IBM awesome! The main steps would be to:

- create an account on the Hugging Face hub (if you don't have one already): https://huggingface.co/join
- optionally, you could create an organisation on the hub, i.e. something like https://huggingface.co/biglam. You can add users to this in a similar way to GitHub. 
- For making the dataset itself available, since you have already hosted it elsewhere,  you could make the dataset available via a loading script: https://huggingface.co/docs/datasets/dataset_script. In this script, you can specify the current URLs used to host the datasets. 
- Since the data is in COCO format you should be able to adapt an existing script. i.e. https://huggingface.co/datasets/ydshieh/coco_dataset_script/blob/main/coco_dataset_script.py or https://huggingface.co/datasets/biglam/nls_chapbook_illustrations. 
- Loading scripts can contain multiple configurations you may want/not want to include, i.e. you could have one configuration that allows for loading the additional document metadata. 

Feel free to ping me if you need any more help with this or have other questions.

**Comment by PeterStaar-IBM** [comment]
Good, we are working on it (HF org: https://huggingface.co/ds4sd)!

**Comment by davanstrien** [comment]
> Good, we are working on it (HF org: [huggingface.co/ds4sd](https://huggingface.co/ds4sd))!

Awesome! Feel free to ping me if you need any assistance.

**Comment by dolfim-ibm** [comment]
@davanstrien We started working on the loader script in https://huggingface.co/datasets/ds4sd/DocLayNet/tree/main

Unfortunately, we are getting errors in the `yield` of the `_generate_examples()` function.
```
File ~/codes/hf_doclaynet/venv/lib/python3.10/site-packages/datasets/features/features.py:1202, in <dictcomp>(.0)
   1200         raise ValueError("Got None but expected a dictionary instead")
   1201     return (
-> 1202         {
   1203             k: encode_nested_example(sub_schema, sub_obj, level=level + 1)
   1204             for k, (sub_schema, sub_obj) in zip_dict(schema, obj)
   1205         }
   1206         if obj is not None
   1207         else None
   1208     )
   1210 elif isinstance(schema, (list, tuple)):

File ~/codes/hf_doclaynet/venv/lib/python3.10/site-packages/datasets/utils/py_utils.py:302, in zip_dict(*dicts)
    300 for key in unique_values(itertools.chain(*dicts)):  # set merge all keys
    301     # Will raise KeyError if the dict don't have the same keys
--> 302     yield key, tuple(d[key] for d in dicts)

File ~/codes/hf_doclaynet/venv/lib/python3.10/site-packages/datasets/utils/py_utils.py:302, in <genexpr>(.0)
    300 for key in unique_values(itertools.chain(*dicts)):  # set merge all keys
    301     # Will raise KeyError if the dict don't have the same keys
--> 302     yield key, tuple(d[key] for d in dicts)

KeyError: 'image_id'

```

Do you have any idea where this could come from? Can you please help us here?

**Comment by davanstrien** [comment]
> Do you have any idea where this could come from? Can you please help us here?

I'll take a look at this (should be able to do this on Monday)

**Comment by PeterStaar-IBM** [comment]
@davanstrien Thank you!

**Comment by dolfim-ibm** [comment]
Thanks @davanstrien.
Is there anything we can do on our side for debugging this error coming from the inside of the `datasets` package?
This seems to be triggered from the loop through the `yield` of the `_generate_examples()`. Already with the first element.

**Comment by davanstrien** [comment]
> Thanks @davanstrien. Is there anything we can do on our side for debugging this error coming from the inside of the `datasets` package? This seems to be triggered from the loop through the `yield` of the `_generate_examples()`. Already with the first element.

Sorry, didn't get a chance to look at this yet but I should be able to take a look first thing tomorrow!

**Comment by davanstrien** [comment]
I'm sorry for not getting back to you sooner. I've just opened a pull request with suggested changes to the dataset loading script. This would result in an instance from the data looking like this:

```python
{'image_id': 1,
 'image': <PIL.PngImagePlugin.PngImageFile image mode=RGB size=1025x1025>,
 'width': 1025,
 'height': 1025,
 'doc_category': 'financial_reports',
 'collection': 'ann_reports_00_04_fancy',
 'doc_name': 'NASDAQ_FFIN_2002.pdf',
 'page_no': 9,
 'objects': [{'category_id': 0,
   'image_id': '1',
   'id': 8,
   'area': 6832,
   'bbox': [210.0601806640625,
    31.145362854003906,
    173.98507690429688,
    39.27094650268555],
   'segmentation': [[210.0601806640625,
     31.145362854003906,
     210.0601806640625,
     70.41630554199219,
     384.0452575683594,
     70.41630554199219,
     384.0452575683594,
     31.145362854003906]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 6,
   'image_id': '1',
   'id': 9,
   'area': 348154,
   'bbox': [434.93341064453125,
    -0.49063488841056824,
    589.8585815429688,
    590.2337646484375],
   'segmentation': [[434.93341064453125,
     -0.49063488841056824,
     434.93341064453125,
     589.7431640625,
     1024.7919921875,
     589.7431640625,
     1024.7919921875,
     -0.49063488841056824]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 7,
   'image_id': '1',
   'id': 10,
   'area': 3974,
   'bbox': [66.99346160888672,
    112.10344696044922,
    290.8693542480469,
    13.662796974182129],
   'segmentation': [[66.99346160888672,
     112.10344696044922,
     66.99346160888672,
     125.76624298095703,
     357.8628234863281,
     125.76624298095703,
     357.8628234863281,
     112.10344696044922]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 9,
   'image_id': '1',
   'id': 11,
   'area': 42722,
   'bbox': [66.99346160888672,
    133.58653259277344,
    325.3560791015625,
    131.31063842773438],
   'segmentation': [[66.99346160888672,
     133.58653259277344,
     66.99346160888672,
     264.89715576171875,
     392.34954833984375,
     264.89715576171875,
     392.34954833984375,
     133.58653259277344]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 9,
   'image_id': '1',
   'id': 12,
   'area': 42737,
   'bbox': [66.99346160888672,
    272.8455810546875,
    325.4856872558594,
    131.30250549316406],
   'segmentation': [[66.99346160888672,
     272.8455810546875,
     66.99346160888672,
     404.1480712890625,
     392.4791564941406,
     404.1480712890625,
     392.4791564941406,
     272.8455810546875]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 9,
   'image_id': '1',
   'id': 13,
   'area': 26326,
   'bbox': [66.99346160888672,
    414.89190673828125,
    325.69677734375,
    80.83059692382812],
   'segmentation': [[66.99346160888672,
     414.89190673828125,
     66.99346160888672,
     495.7225036621094,
     392.69024658203125,
     495.7225036621094,
     392.69024658203125,
     414.89190673828125]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 9,
   'image_id': '1',
   'id': 14,
   'area': 268406,
   'bbox': [112.37567138671875,
    626.7556762695312,
    863.1117553710938,
    310.9754333496094],
   'segmentation': [[112.37567138671875,
     626.7556762695312,
     112.37567138671875,
     937.7311401367188,
     975.4874267578125,
     937.7311401367188,
     975.4874267578125,
     626.7556762695312]],
   'iscrowd': False,
   'precedence': 0},
  {'category_id': 4,
   'image_id': '1',
   'id': 15,
   'area': 77,
   'bbox': [18.3287410736084,
    1005.2406616210938,
    7.449673175811768,
    10.353534698486328],
   'segmentation': [[18.3287410736084,
     1005.2406616210938,
     18.3287410736084,
     1015.5941772460938,
     25.77841567993164,
     1015.5941772460938,
     25.77841567993164,
     1005.2406616210938]],
   'iscrowd': False,
   'precedence': 0}]}
```

There are probably a few other bits of the script that could be tidied, but I thought I should pass this by you first. 
This format is intended to match other object detection datasets hosted on the Hugging Face hub more closely.

**Comment by dolfim-ibm** [comment]
Many thanks @davanstrien, we would never have gotten to the right data format without your help!
