### ISSUE TITLE
What is the meaning of the key segmentation of an image annotation?

### ISSUE THREAD

**Issue by piegu** [DS4SD/DocLayNet#14]
Hi,

in the train/val/test json files (ex: `train.json`) in the folder `COCO`, a` key `of each image annotation is `segmentation`. 

I do not find any explanation about this field. 
Could you give some? Thank you.

```
 "annotations": [
    {
      "id": 8,
      "image_id": 1,
      "category_id": 1,
      "bbox": [
        210.06018382352943,
        31.14536268939389,
        173.9850743464052,
        39.270946654040586
      ],
      "segmentation": [
        [
          210.06018382352943,
          31.14536268939389,
          210.06018382352943,
          70.41630934343448,
          384.04525816993464,
          70.41630934343448,
          384.04525816993464,
          31.14536268939389
        ]
      ],
      "area": 6832.558573256964,
      "iscrowd": 0,
      "precedence": 0
    },
```

**Comment by cau-git** [comment]
Hello @piegu, 
the `segmentation` describes a polygon that is identical to the `bbox`, as the COCO format defines [here](https://cocodataset.org/#format-data). You can choose to work either with `bbox` or `segmentation`, depending on what your training code supports better.

**Comment by piegu** [comment]
Thank you @cau-git.
