### ISSUE TITLE
Many Images missing in the PNG folder 

### ISSUE THREAD

**Issue by Anang1502** [DS4SD/DocLayNet#19]
Hi,
As per the documentation, there are 80863 images used for annotations. I downloaded the 28GB DocLayNet Core file. In the PNG folder, I can only see 69849 images. Although when I totaled the number of images used for annotations in train, test, and validation json they come out to be exactly 80863 images. There seem to be around 11014 (80863 - 69849) missing images in PNG folder. Can you please tell me where can I get the missing image data?

**Comment by nassarofficial** [comment]
Hello,
Thank you for using our dataset. We recommend that you redownload the zip file, the size should be 30.01GB. I downloaded the zip file and extracted it, and there should be 81,471 files in the PNG folder.
![dlncount](https://user-images.githubusercontent.com/4061978/218696087-027cdec2-74ad-415c-853f-1674f65bccda.jpg)
