### ISSUE TITLE
There seems to be no papers in the dataset?

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [DS4SD/DocLayNet#20]
![QQ截图20230506003401](https://user-images.githubusercontent.com/21216881/236515828-fe7e34bd-e927-4071-ba0b-973e4076dc0d.png)

https://ds4sd.github.io/icdar23-doclaynet/#participation

**Comment by cau-git** [comment]
DocLayNet contains the following document categories: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/60343111/237023188-f6ecee93-4544-443a-908f-2ed8839d05c0.png">

In the coco.json, the image identifiers expose a field `doc_category`, see [here](https://github.com/DS4SD/DocLayNet#example-coco-image-record). The samples of paper pages are tagged with `scientific_articles`.

**Comment by xiaoguaishoubaobao** [comment]
Thank you very much for your reply
Will there be more paper added in the future?

**Comment by cau-git** [comment]
Hi @xiaoguaishoubaobao, we are not planning to focus on more papers right now, since this is already well covered in the previous [PubLayNet dataset](https://github.com/ibm-aur-nlp/PubLayNet).

**Comment by xiaoguaishoubaobao** [comment]
Thank you very much for your reply!

Thank you for your great work!
