### ISSUE TITLE
Labeling Guidline

### ISSUE THREAD

**Issue by moured** [DS4SD/DocLayNet#3]
Thanks a lot for the great work. you promised in the paper to make the 100-page labelling guidelines available to the community. Could you please upload it as well? :)

Have a great day,
Omar

**Comment by cau-git** [comment]
@moured Thanks for bringing this to our attention. We are currently preparing the labelling guideline for publication and will add it to the README soon.

**Comment by cau-git** [comment]
fixed by https://github.com/DS4SD/DocLayNet/pull/4

@moured The guideline is now available for download on the README.

**Comment by moured** [comment]
@cau-git **Disciplined team and great work, Thanks!**
