### ISSUE TITLE
Issue with text cell bbox coordinates in JSON file

### ISSUE THREAD

**Issue by iiLaurens** [DS4SD/DocLayNet#7]
Consider the page with page_hash `993d6cf77a098e7c33f94be7382ade6bb106003b238d16e4a8483a6580ecf72a`.

The metadata for this page equals:
```python
{'page_hash': '993d6cf77a098e7c33f94be7382ade6bb106003b238d16e4a8483a6580ecf72a',
 'original_filename': 'NYSE_TDS_2001.pdf',
 'page_no': 0,
 'num_pages': 40,
 'original_width': 603,
 'original_height': 792,
 'coco_width': 1025,
 'coco_height': 1025,
 'collection': 'ann_reports_00_04_fancy',
 'doc_category': 'financial_reports'}
```

Which corresponds to the image:
![img](https://user-images.githubusercontent.com/9915637/191255400-5939df40-0530-4bb1-93de-58a8bc57fb85.png)

The JSON file gives me the following cells. Note that according to the documentation, the bbox coordinates are of the form:
[x0,x1,y0,y1] where point (x0,y0) is the bottom left corner and point (x1, y1) is the top right corner in the coordinate system (0, 0, original_width, original_height).

```python
[{'bbox': [374.5325862354892,
   296.91633143939407,
   273.19044527363184,
   14.17915372474738],
  'text': 'Telephone and Data Systems Inc.',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAHMFF+Univers-Condensed',
   'size': 1}},
 {'bbox': [461.07316625207295,
   324.0943617424243,
   100.13179104477604,
   14.17915372474738],
  'text': 'U.S. Cellular',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAHMFF+Univers-Condensed',
   'size': 1}},
 {'bbox': [457.3423362354892,
   344.80087594696965,
   107.58722968490878,
   14.179166666666788],
  'text': 'TDS Telecom',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAHMFF+Univers-Condensed',
   'size': 1}},
 {'bbox': [411.6026376451078,
   605.223790719697,
   548.3724842454394,
   16.46524021464643],
  'text': 'Serving our customers over the decades',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAILEB+Univers-Black',
   'size': 1}},
 {'bbox': [795.037663349917,
   967.3200688762627,
   54.42187354892212,
   14.163631186868685],
  'text': '2001',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAILEB+Univers-Black',
   'size': 1}},
 {'bbox': [854.4386911276948,
   967.3200688762627,
   105.48207006633504,
   14.179162784090906],
  'text': 'Annual Report',
  'font': {'color': [0, 0, 0, 255],
   'name': '/DAHMFF+Univers-Condensed',
   'size': 1}}]
```

To me it seems there are at least two things wrong with the coordinates in the JSON files.

First of all, an X-coordinate usually corresponds to the horizontal dimension and the Y coordinate corresponds to the vertical dimension. But consider the text cells "U.S. Cellular" and "TDS Telecom". Both text cells have  `y1 = 14.179`. This suggests they are positioned at the same height. The image clearly reveals however that they are vertically stacked. This contradicts the `y1` shared values.

The second issue is the coordinate system. The readme states: 
```Bounding-box coordinates of text cells formatted as [x0,x1,y0,y1] where (x0,y0) is the lower-left corner and (x1,y1) is the top-right corner in the coordinate space of (0,0, original_width, original_height)```
But now look at the very last text cell with the text "Annual Report". Notice that `x0 = 864.42` and `x1 = 967.32`. These points are beyond the original_width of 603. Looking at the image, the text is clearly visible. So it can't be that the text happens to be outside of the PDF cropbox. So it seems to me that the description in the readme is wrong. How can this text be beyond the coordinate system?

Could you have a second look at the correctness of these coordinates?

**Comment by marcoaleixo** [comment]
bump

**Comment by cau-git** [comment]
@iiLaurens Well spotted, and sorry for the delayed response. You have in fact discovered a documentation mistake.
@marcoaleixo FYI.

The cell bounding box definitions in this JSON file actually match the COCO format annotations on the PNG images, meaning:

- Coordinate origin: upper left corner
- Coordinate space: (0,0) to (1025,1025)
- Coordinate specification: (x, y, width, height) where (x,y) is the upper-left corner of a cell bounding box.

As such, no transforms are necessary between the cell bounding-boxes you find here and the annotation bounding boxes on the COCO files. Both relate to the PNG image.
