### ISSUE TITLE
The annotation tool used to build the dataset

### ISSUE THREAD

**Issue by Scallions** [DS4SD/DocLayNet#8]
Thanks for the good job. I want to annotate ourself documents. So I want know what tool used to build dataset

**Comment by cau-git** [comment]
HI @Scallions, we use a proprietary annotation tool developed within our [Deep Search](https://ds4sd.github.io/) platform. We can unfortunately not make it available to the public.

Annotating new material should work fine also with any other bounding box annotation tool for COCO format.

**Comment by Scallions** [comment]
Yeah, I find another annotaing tool and I trained a model using this dataset which work well on my job. 😃 
Thanks for the hardwork on this dataset.

**Comment by piegu** [comment]
Hi @Scallions. Can you share the name and url of the document annotation tool you used? 

We are many in the Document AI community looking for such an Open Source tool.

**Comment by Scallions** [comment]
https://github.com/open-mmlab/labelbee-client
https://github.com/heartexlabs/label-studio

Label-studio has more function.
